title: Total Defence Logo Public Design Competition 2019
remote_theme: opendocsg/opendoc-theme@v2
timezone: Asia/Singapore
repository: opendocsg/opendoc-total-defence-logo-design-competition
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics:  
styling_options:
  primary_brand_color: '#822c30'
  logo_path: /assets/logo.jpg
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url:  #----> Optional, feedback url
